/* library-export.js — generate BibTeX (and helpers) for a draft paper.
 *
 * Source of truth for "which papers are cited":
 *   - All evidence on claims attached to the draft
 *     (Firestore: drafts/{draftId}/claims/{claimId}.{supporting,counter}_evidence_ids)
 *   - Each evidence entry is {paperId, annId}; the source-of-citation paper
 *     is whichever paper the annotation lives on.
 *
 * Public API (window.LIBRARY_EXPORT):
 *   citedPaperIds(draftId)            → Promise<string[]>  unique paperIds
 *   buildBibtex(draftId, items)       → Promise<{bibtex, cited, missing, draft}>
 *   downloadBibtex(draftId, items, repoPath?, filename?)
 *   writeToRepo(draftId, items, repoPath, filename?)  (server-side write)
 */
(function () {
  function _esc(s) { return String(s ?? ''); }

  /** Walk drafts/{draftId}/claims/* once and return unique source-paper ids. */
  async function citedPaperIds(draftId) {
    if (typeof firebase === 'undefined' || !firebase.firestore) {
      throw new Error('Firestore SDK not loaded.');
    }
    const snap = await firebase.firestore()
      .collection('drafts').doc(draftId)
      .collection('claims').get();
    const ids = new Set();
    snap.docs.forEach(d => {
      const c = d.data();
      (c.supporting_evidence_ids || []).forEach(e => e && e.paperId && ids.add(e.paperId));
      (c.counter_evidence_ids || []).forEach(e => e && e.paperId && ids.add(e.paperId));
    });
    return Array.from(ids);
  }

  function _authorList(authors) {
    if (!Array.isArray(authors) || !authors.length) return '';
    // BibTeX wants "Family, Given and Family, Given and …"
    return authors.map(a => {
      const fam = (a.family || '').trim();
      const giv = (a.given || '').trim();
      if (fam && giv) return `${fam}, ${giv}`;
      return fam || giv;
    }).filter(Boolean).join(' and ');
  }

  function _bibField(key, value) {
    if (value == null || value === '') return '';
    // Escape % and backslash for BibTeX; preserve special chars otherwise.
    const s = String(value).replace(/[\\]/g, '\\\\').replace(/%/g, '\\%');
    return `  ${key} = {${s}},\n`;
  }

  function _bibType(meta) {
    if (meta.arxiv_id && !meta.doi) return 'misc';        // preprint
    if (meta.journal) return 'article';
    return 'article';
  }

  /** Render one paper item as a BibTeX entry. */
  function _entryFor(item) {
    const lib = (item.meta || {}).library || {};
    const key = lib.citation_key || _slug(item.id) || 'noKey';
    const type = _bibType(lib);
    let body = `@${type}{${key},\n`;
    body += _bibField('title', item.title);
    body += _bibField('author', _authorList(lib.authors));
    body += _bibField('journal', lib.journal);
    body += _bibField('year', lib.year);
    body += _bibField('volume', lib.volume);
    body += _bibField('number', lib.issue);
    body += _bibField('pages', lib.pages);
    body += _bibField('doi', lib.doi);
    body += _bibField('url', lib.url || (lib.doi ? `https://doi.org/${lib.doi}` : ''));
    if (lib.arxiv_id) body += _bibField('eprint', lib.arxiv_id);
    if (lib.pmid) body += _bibField('pmid', lib.pmid);
    if (lib.abstract) {
      // Trim long abstracts to keep the .bib file manageable.
      const abs = String(lib.abstract).replace(/\s+/g, ' ').trim().slice(0, 1500);
      if (abs) body += _bibField('abstract', abs);
    }
    body += '}\n';
    return { key, body };
  }

  function _slug(s) {
    return String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '').slice(0, 60);
  }

  /**
   * Build the full BibTeX file content for a draft.
   * `items` is the items.json `items` array.
   * Returns { bibtex, cited: paperItems[], missing: paperIds[], draft }.
   */
  async function buildBibtex(draftId, items) {
    const draft = items.find(it => it.id === draftId);
    const ids = await citedPaperIds(draftId);
    const idSet = new Set(ids);
    const cited = items.filter(it => idSet.has(it.id) && it.type === 'paper');
    const foundIds = new Set(cited.map(it => it.id));
    const missing = ids.filter(id => !foundIds.has(id));

    // Sort by citation key for deterministic output.
    cited.sort((a, b) => {
      const ak = ((a.meta || {}).library || {}).citation_key || a.id;
      const bk = ((b.meta || {}).library || {}).citation_key || b.id;
      return ak.localeCompare(bk);
    });

    const today = new Date().toISOString().slice(0, 10);
    const draftTitle = (draft && draft.title) || draftId;
    let bibtex = '';
    bibtex += `% refs.bib — generated by ResearchManagement library-export.js\n`;
    bibtex += `% draft: ${draftTitle} (id: ${draftId})\n`;
    bibtex += `% generated: ${today}\n`;
    bibtex += `% entries:  ${cited.length}\n`;
    if (missing.length) {
      bibtex += `% missing in items.json (evidence link broken): ${missing.join(', ')}\n`;
    }
    bibtex += '\n';
    for (const item of cited) {
      const { body } = _entryFor(item);
      bibtex += body + '\n';
    }
    return { bibtex, cited, missing, draft };
  }

  /** Trigger a browser download of the generated .bib. */
  async function downloadBibtex(draftId, items, filename) {
    const { bibtex, draft } = await buildBibtex(draftId, items);
    const fname = filename || `refs.${(draft && draft.id) || draftId}.bib`;
    const blob = new Blob([bibtex], { type: 'application/x-bibtex;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fname;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
    return { count: bibtex.split('\n').filter(l => l.startsWith('@')).length };
  }

  /** POST the generated .bib to server.py to write into the sibling repo. */
  async function writeToRepo(draftId, items, repoPath, filename) {
    const { bibtex, cited, missing } = await buildBibtex(draftId, items);
    const res = await fetch('/api/library/write-bib', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        repo_path: repoPath,
        filename: filename || 'refs.bib',
        content: bibtex,
        draft_id: draftId,
      }),
    });
    if (!res.ok) {
      const detail = await res.text().catch(() => res.statusText);
      throw new Error(`write-bib failed (${res.status}): ${detail}`);
    }
    const data = await res.json();
    return Object.assign({ cited_count: cited.length, missing }, data);
  }

  window.LIBRARY_EXPORT = {
    citedPaperIds,
    buildBibtex,
    downloadBibtex,
    writeToRepo,
  };
})();
