/* paper-schemas.js — closed vocabularies and default templates for the paper builder.
 *
 * Phase A scope: paragraph blocks only (skeleton + body). Equation, figure, table,
 * and list block kinds are reserved for Phase C; they're declared here so the
 * editor can render an "(unsupported in this phase)" placeholder for any tree
 * loaded from a future version.
 *
 * The vocabularies must stay in sync with `paper_md.py` (Phase E) and with the
 * LaTeX templates in `data/paper-templates/` (Phase F).
 */

(function () {
  /* Section kinds — closed list. `custom` is the escape hatch (free-form label). */
  var PAPER_SECTION_KINDS = [
    'abstract',
    'keywords',
    'introduction',
    'background',
    'methods',
    'results',
    'discussion',
    'conclusions',
    'acknowledgements',
    'references',
    'custom',
  ];

  var SECTION_KIND_LABELS = {
    abstract: 'Abstract',
    keywords: 'Keywords',
    introduction: 'Introduction',
    background: 'Background',
    methods: 'Materials and Methods',
    results: 'Results',
    discussion: 'Discussion',
    conclusions: 'Conclusions',
    acknowledgements: 'Acknowledgements',
    references: 'References',
    custom: 'Custom Section',
  };

  /* Per-section style/policy. Phase A respects only the structural fields
   * (allowFigures, allowSubsections, allowInventoryQuickInsert). Word counts
   * are advisory. Phase D will enforce maxWords at status=complete. */
  var SECTION_STYLE = {
    abstract:        { maxWords: 250, allowFigures: false, allowEquations: false, allowSubsections: false },
    keywords:        { maxWords: 30,  allowFigures: false, allowEquations: false, allowSubsections: false },
    introduction:    { allowFigures: true,  allowEquations: true,  allowSubsections: true },
    background:      { allowFigures: true,  allowEquations: true,  allowSubsections: true },
    methods:         { allowFigures: true,  allowEquations: true,  allowSubsections: true,
                       allowInventoryQuickInsert: true },
    results:         { allowFigures: true,  allowEquations: true,  allowSubsections: true },
    discussion:      { allowFigures: true,  allowEquations: true,  allowSubsections: true },
    conclusions:     { allowFigures: false, allowEquations: false, allowSubsections: false },
    acknowledgements:{ allowFigures: false, allowEquations: false, allowSubsections: false },
    references:      { allowFigures: false, allowEquations: false, allowSubsections: false,
                       autoGenerated: true },
    custom:          { allowFigures: true,  allowEquations: true,  allowSubsections: true },
  };

  /* Block kinds — Phase A renders only `paragraph`. Others are declared so
   * stored docs from later phases parse without crashing. */
  var PAPER_BLOCK_KINDS = ['paragraph', 'equation', 'figure', 'table', 'list'];

  var BLOCK_STATUSES = ['draft', 'needs-review', 'complete'];

  /* Default templates — controls which sections seed a new paper. The
   * `template_id` on each paper in papers.json picks one of these. Authors can
   * add/remove sections freely after creation; the template is just a starter. */
  var PAPER_TEMPLATES = {
    'mebp-journal': {
      id: 'mebp-journal',
      name: 'Journal article (MEBP-style)',
      description: 'Standard journal article structure: abstract, intro, methods, results, discussion, conclusion.',
      sections: [
        { kind: 'abstract',     label: 'Abstract' },
        { kind: 'introduction', label: 'Introduction' },
        { kind: 'methods',      label: 'Materials and Methods' },
        { kind: 'results',      label: 'Results' },
        { kind: 'discussion',   label: 'Discussion' },
        { kind: 'conclusions',  label: 'Conclusion' },
      ],
    },
    'nih-r01': {
      id: 'nih-r01',
      name: 'NIH R01 Research Strategy',
      description: 'Specific Aims + Significance/Innovation/Approach.',
      sections: [
        { kind: 'custom',       label: 'Specific Aims' },
        { kind: 'background',   label: 'Significance' },
        { kind: 'custom',       label: 'Innovation' },
        { kind: 'methods',      label: 'Approach' },
      ],
    },
    'blank': {
      id: 'blank',
      name: 'Blank',
      description: 'No starter sections. Build your own outline.',
      sections: [],
    },
  };

  /* ── Tree helpers ── */

  /* Crockford-base32 short id, ~7 chars, ~35 bits. Plenty for per-paper uniqueness. */
  function shortId(prefix) {
    var alphabet = '0123456789abcdefghjkmnpqrstvwxyz';
    var s = '';
    for (var i = 0; i < 7; i++) s += alphabet[Math.floor(Math.random() * alphabet.length)];
    return (prefix || '') + s;
  }

  function newSection(kind, label, order) {
    var k = PAPER_SECTION_KINDS.indexOf(kind) >= 0 ? kind : 'custom';
    return {
      id: shortId('sec-'),
      kind: k,
      label: label || SECTION_KIND_LABELS[k] || 'Untitled section',
      order: order || 0,
      style_overrides: {},
      status: 'draft',
      children: [],
    };
  }

  function newParagraph() {
    return {
      id: shortId('p-'),
      kind: 'paragraph',
      status: 'draft',
      skeleton: '',
      body: '',
      attrs: {},
    };
  }

  /* Build a fresh paper tree from a template id. */
  function newTree(templateId, paperTitle) {
    var tpl = PAPER_TEMPLATES[templateId] || PAPER_TEMPLATES['blank'];
    var sections = (tpl.sections || []).map(function (s, i) {
      var sec = newSection(s.kind, s.label, i);
      // Seed each section with one empty paragraph so the editor isn't a wall of empty headers.
      sec.children.push(newParagraph());
      return sec;
    });
    return {
      meta: { title: paperTitle || '' },
      sections: sections,
    };
  }

  /* Validate a loaded tree — coerces missing fields, keeps last-known-good shape. */
  function normalizeTree(tree) {
    if (!tree || typeof tree !== 'object') tree = {};
    if (!tree.meta) tree.meta = {};
    if (!Array.isArray(tree.sections)) tree.sections = [];
    tree.sections.forEach(function (sec, i) {
      if (!sec.id) sec.id = shortId('sec-');
      if (PAPER_SECTION_KINDS.indexOf(sec.kind) < 0) sec.kind = 'custom';
      if (typeof sec.label !== 'string') sec.label = SECTION_KIND_LABELS[sec.kind] || 'Untitled';
      if (typeof sec.order !== 'number') sec.order = i;
      if (!sec.style_overrides) sec.style_overrides = {};
      if (BLOCK_STATUSES.indexOf(sec.status) < 0) sec.status = 'draft';
      if (!Array.isArray(sec.children)) sec.children = [];
      sec.children.forEach(function (blk) {
        if (!blk.id) blk.id = shortId('p-');
        if (PAPER_BLOCK_KINDS.indexOf(blk.kind) < 0) blk.kind = 'paragraph';
        if (BLOCK_STATUSES.indexOf(blk.status) < 0) blk.status = 'draft';
        if (typeof blk.skeleton !== 'string') blk.skeleton = '';
        if (typeof blk.body !== 'string') blk.body = '';
        if (!blk.attrs) blk.attrs = {};
      });
    });
    // Reorder by `order`, then renormalize indices for predictable saves.
    tree.sections.sort(function (a, b) { return (a.order || 0) - (b.order || 0); });
    tree.sections.forEach(function (sec, i) { sec.order = i; });
    return tree;
  }

  function styleFor(section) {
    var base = SECTION_STYLE[section.kind] || SECTION_STYLE.custom;
    return Object.assign({}, base, section.style_overrides || {});
  }

  /* Public surface */
  window.PaperSchemas = {
    PAPER_SECTION_KINDS: PAPER_SECTION_KINDS,
    SECTION_KIND_LABELS: SECTION_KIND_LABELS,
    SECTION_STYLE: SECTION_STYLE,
    PAPER_BLOCK_KINDS: PAPER_BLOCK_KINDS,
    BLOCK_STATUSES: BLOCK_STATUSES,
    PAPER_TEMPLATES: PAPER_TEMPLATES,
    shortId: shortId,
    newSection: newSection,
    newParagraph: newParagraph,
    newTree: newTree,
    normalizeTree: normalizeTree,
    styleFor: styleFor,
  };
})();
